site_name: CSSE4011 Tutorial Docs
site_url: https://github.com/uqembeddedsys-projects/csse4011_zephyr_guides
repo_url: https://github.com/uqembeddedsys-projects/csse4011_zephyr_guides
repo_name:  csse4011_zephyr_guides



nav:
  - Contents: about.md
  - Operating System: 
      - 'Overview' : OS/about.md
      - '1.0 Getting Started': OS/OS.1-Getting_Started.md
      - '2.0 First Program': OS/OS.2-First_Program.md
      - '2.1 Building Tips': OS/OS.2.1-Building_Tips.md
      - '2.2 Implementing Libraries': OS/OS.2.2-Implementing_Libraries.md
      - '4.0 Threading': OS/OS.4-Threading.md
      - '5.1 Thread Synchronization': OS/OS.5.1-Thread_Sync.md
      - '5.2 Thread Communication': OS/OS.5.2-Thread_Communication.md
  - Connectivity: 
      - 'Overview': Connectivity/about.md
      - '1.0 GPIO' : Connectivity/CN.1-GPIO.md
      - '2.0 Sensors': Connectivity/CN.2-Sensors.md
      - '3.0 Serial Console': Connectivity/CN.3-Serial_Console.md
      - '4.0 Shell': Connectivity/CN.4-Shell.md
      - '4.1 Shell Commands': Connectivity/CN.4.1-Shell_Commands.md
      - '5.0 Logging': Connectivity/CN.5-Logging.md
      - '6.0 Segger RTT': Connectivity/CN.6-Segger_RTT.md

  - Boards: 
      - 'Overview' : Boards/about.md
      - '1.0 Arduino Sense BLE': Boards/BRD.1-Arduino_Sense.md
      - '2.0 Thingy52': Boards/BRD.2-Thingy52.md
      - '3.0 nRF Dongle': Boards/BRD.3-Dongle_NRF52840.md
      - '4.0 Particle Argon': Boards/BRD.4-Particle_Argon.md



theme: 
    name: material
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
     
    features:
        - header.autohide
        - content.code.annotate
    font:
        text: Roboto
    
    icon:
        repo: fontawesome/brands/git-alt

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
  - search
  - git-revision-date:

extra:
  version: 1.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thulithwilfred


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

